# Generated by Django 4.2.6 on 2024-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0004_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preço',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='000,00', max_digits=10),
        ),
    ]
