# Generated by Django 4.2.6 on 2024-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0005_remove_produto_preço_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='00,00', max_digits=10),
        ),
    ]
